version: '3.8'

services:
  kr-studio-app:
    build:
      context: .
      dockerfile: Dockerfile.simple
    ports:
      - "10000:10000"
    environment:
      - NODE_ENV=production
      - PORT=10000
    volumes:
      - ./uploads:/app/uploads
      - ./separated:/app/separated
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:10000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  # Optional: Redis for caching (if needed)
  # redis:
  #   image: redis:alpine
  #   ports:
  #     - "6379:6379"
  #   restart: unless-stopped

networks:
  default:
    name: kr-studio-network
