# fly.toml app configuration file generated for kr-studio-completeai on 2025-08-11T08:18:04Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "kr-studio-completeai"
primary_region = "fra"

[build]
  builder = "heroku/builder:22"

[env]
  NODE_ENV = "production"
  PORT = "10000"

[http_service]
  internal_port = 10000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  grace_period = "60s"
  interval = "30s"
  method = "GET"
  timeout = "10s"
  path = "/api/health"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[mounts]
  source = "kr_studio_data"
  destination = "/app/uploads"
