services:
  - type: web
    name: kr-studio-completeai
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: WORKER_URL
        value: https://kr-studio-worker.onrender.com/api/worker
    disk:
      name: audio-storage
      mountPath: /opt/render/project/src
      sizeGB: 1
    autoDeploy: true
    branch: main
    repo: https://github.com/your-username/kr-studio-completeai
