services:
  # Web Service - ה-API/אתר הראשי
  - type: web
    name: kr-studio-completeai
    env: node
    plan: free
    buildCommand: npm ci --prefer-offline && npm run build
    startCommand: node server.js
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: WORKER_MODE
        value: false
    disk:
      name: audio-storage
      mountPath: /opt/render/project
      sizeGB: 1
    autoDeploy: true
    branch: main
    repo: https://github.com/roizohar199/KR-STUDIO-CompleteAI.git

  # Background Worker - Demucs Worker Manager
  - type: background
    name: demucs-worker-manager
    env: node
    plan: free
    buildCommand: npm ci --prefer-offline && pip install -r requirements.txt
    startCommand: node demucs-node-worker.cjs
    envVars:
      - key: NODE_ENV
        value: production
      - key: WORKER_MODE
        value: true
      - key: MAX_WORKERS
        value: "2"
      - key: TASK_TIMEOUT
        value: "900000"
    autoDeploy: true
    branch: main
    repo: https://github.com/roizohar199/KR-STUDIO-CompleteAI.git
