services:
  - type: web
    name: kr-studio-audio-separation
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /api/health
    healthCheckTimeout: 180
    autoDeploy: true
    buildFilter:
      paths:
        - "**/*" 